version: '3'

services:
  # prosinic:
  #   build: 
  #     context: .
  #     dockerfile: DockerFile
  #   volumes:
  #     - .:/prosinic_backend_core
  #     - prosonic_uploads_volume:/prosinic_backend_core/uploads
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - postgres_network
  #   depends_on:
  #     - prosonic_postgresql

  prosonic_postgresql:
    image: postgres:14.4
    container_name: prosonic_postgresql
    volumes:
      - prosonic_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - postgres_network


volumes:
  prosonic_postgresql:
    external: true 
  # prosonic_uploads_volume:
  #   external: true  
networks:
  postgres_network:
    external: true 