version: '3'

services:
  prosinic:
    build: 
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/prosinic
      - ./uploads:/prosonic/uploads
      - ./prosonic_backend_core/static:/prosonic/static
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres_network
    depends_on:
      - prosonic_postgresql

  prosonic_postgresql:
    image: postgres:14.4
    container_name: prosonic_postgresql
    volumes:
      - prosonic_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - postgres_network


volumes:
  prosonic_postgresql:
    external: true 
networks:
  postgres_network:
    external: true 