version: '3'

services:
  prosonic:
    build: 
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/prosinic
      - ./uploads:/prosonic/uploads
      - ./static:/prosonic/static
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres_network
    depends_on:
      - postgresql_db

  postgresql_db:
    image: postgres:14.4
    container_name: postgresql_db
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - postgres_network


volumes:
  postgresql_db:
    external: true 
networks:
  postgres_network:
    external: true 