# Generated by Django 4.1 on 2022-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
