# Generated by Django 4.1 on 2022-08-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="product_id",
        ),
        migrations.AddField(
            model_name="product",
            name="file_id",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.file",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cover_price",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="overall_price",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="package_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="sample_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="stem_price",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
