# Generated by Django 4.1 on 2022-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="demo_file",
            field=models.FileField(max_length=254, upload_to=None),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(max_length=254, upload_to=None),
        ),
    ]
