# Generated by Django 4.1 on 2022-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_file_demo_file_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="demo_file",
            field=models.FileField(
                max_length=254, upload_to="uploads/files/{self.file_name}"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                max_length=254, upload_to="uploads/files/{self.file_name}"
            ),
        ),
    ]
