# Generated by Django 4.1 on 2022-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_file_demo_file_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="demo_file",
            field=models.FileField(max_length=254, upload_to="uploads/files/demo"),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(max_length=254, upload_to="uploads/files/main"),
        ),
        migrations.AlterField(
            model_name="product",
            name="project_image",
            field=models.ImageField(
                max_length=254, upload_to="uploads/images/products"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                max_length=254, upload_to="uploads/images/products"
            ),
        ),
    ]
