# Generated by Django 4.1 on 2022-08-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_product_cover_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cover_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="overall_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stem_price",
        ),
    ]
