# Generated by Django 4.1 on 2022-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_alter_product_bpm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="project_image",
            field=models.ImageField(
                blank=True,
                max_length=254,
                null=True,
                upload_to="uploads/images/products",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=254,
                null=True,
                upload_to="uploads/images/products",
            ),
        ),
    ]
