# Generated by Django 4.1 on 2022-08-15 09:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_alter_product_cover_price_alter_product_stem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="file_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="project_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stem_price",
            field=models.DecimalField(
                blank=True,
                choices=[
                    ("beat", "Beat"),
                    ("track", "Track"),
                    ("service", "Service"),
                    ("package", "Package"),
                ],
                decimal_places=0,
                max_digits=10,
                null=True,
            ),
        ),
    ]
