# Generated by Django 4.1 on 2022-08-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_product_file_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="cover",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to="uploads/files/cover"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="stem",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to="uploads/files/stem"
            ),
        ),
    ]
