# Generated by Django 4.1 on 2022-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_file_cover_file_stem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beat", "Beat"),
                    ("track", "Track"),
                    ("service", "Service"),
                    ("package", "Package"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stem_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
    ]
