# Generated by Django 4.1 on 2022-08-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_alter_product_daw_alter_product_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="daw",
            field=models.CharField(
                blank=True,
                choices=[("Cubase", "Cubase"), ("FLStudio", "FLStudio")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Track", "Track"),
                    ("Service", "Service"),
                    ("Package", "Package"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
