# Generated by Django 4.1 on 2022-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_userprofile_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(max_length=254, upload_to="uploads/images/avatar"),
        ),
    ]
