# Generated by Django 4.1 on 2022-08-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user_id",
            new_name="user",
        ),
    ]
