# Generated by Django 4.1 on 2022-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_rename_user_id_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, max_length=254, null=True, upload_to="uploads/images/avatar"
            ),
        ),
    ]
